import type { Metadata } from "next";
import {Montserrat } from "next/font/google";
import "./globals.css";

const montserrat =Montserrat({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className + " py-20 px-2"}>
        <div className="w-full max-w-6xl mx-auto">

        {children}
        </div>
        </body>
    </html>
  );
}
